### ISSUE TITLE
Gap in incident / event information

### ISSUE THREAD

**Issue by zigsphere** [zigsphere/odot-cameras#4]
If there are both incidents and events, there is sometimes gaps between the two if incidents has an uneven amount of events.
![gap](https://user-images.githubusercontent.com/4658061/152285862-ace540e1-9949-4a73-9944-5f97843428d1.png)

**Comment by Aankhen** [comment]
If you want them to be treated as a unit, you can put them all in the same `ul`. Just make sure you have the correct logic for when there should be a `ul` (either of them is non-empty) and when there shouldn’t (both of them are empty).

**Comment by zigsphere** [comment]
fixed!
